version: '3.7'

services:

  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kutala-golang
    restart: always
    ports:
      - '9000:9000'
    networks:
      - host
    depends_on:
      - prometheus
      - db

  db:
    image: postgres:9.4
    container_name: kutala-postgres
    tty: true
    restart: always
    volumes:
      - kutala-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kutalagateway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - host

  prometheus:
    image: prom/prometheus:latest
    container_name: kutala-prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - kutala-prometheus:/prometheus
    ports:
      - 9090:9090

networks:
  host: {}

volumes:
  kutala-postgres:
  kutala-prometheus: