version: '3'

services:
  db:
   image: postgres:9.4
   container_name: kutala-postgres
   restart: always
   deploy:
      replicas: 3
   tty: true
   volumes:
     - ./utils/database/postgresql/.pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"
   networks:
      - postgres

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: kutala-pgadmin
    restart: always
    deploy:
      replicas: 3
    tty: true
    volumes:
      - ./utils/database/postgresql/.pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pl1745240@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "8000:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  kutala-postgres:
  kutala-pgadmin: