global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: monitoring 
    metrics_path: /metrics
    static_configs:
    - targets: 
      - localhost:9000
      - localhost:9090
